var searchData=
[
  ['dados_0',['Erros de dados',['../db/dda/md__testes_01e_01erros.html#erros-de-dados',1,'']]],
  ['de_20alocação_20de_20memória_1',['Erro 2.1: Erro de alocação de memória',['../db/dda/md__testes_01e_01erros.html#erro-21-erro-de-alocação-de-memória',1,'']]],
  ['de_20arquivo_20inválido_2',['Erro 1.3: Nome de arquivo inválido',['../db/dda/md__testes_01e_01erros.html#erro-13-nome-de-arquivo-inválido',1,'']]],
  ['de_20arquivos_3',['Erros de arquivos',['../db/dda/md__testes_01e_01erros.html#erros-de-arquivos',1,'']]],
  ['de_20array_20de_20jogadores_20nulo_4',['Erro 2.2: Passagem de array de jogadores nulo',['../db/dda/md__testes_01e_01erros.html#erro-22-passagem-de-array-de-jogadores-nulo',1,'']]],
  ['de_20array_20de_20jogadores_20vazio_5',['Erro 2.3: Passagem de array de jogadores vazio',['../db/dda/md__testes_01e_01erros.html#erro-23-passagem-de-array-de-jogadores-vazio',1,'']]],
  ['de_20atacante_20inválido_6',['Erro 3.4: Índice de atacante inválido',['../db/dda/md__testes_01e_01erros.html#erro-34-índice-de-atacante-inválido',1,'']]],
  ['de_20bugs_7',['Lista de Bugs',['../de/da5/bug.html',1,'']]],
  ['de_20dados_8',['Erros de dados',['../db/dda/md__testes_01e_01erros.html#erros-de-dados',1,'']]],
  ['de_20erros_9',['Código de erros',['../db/dda/md__testes_01e_01erros.html#código-de-erros',1,'']]],
  ['de_20escrita_10',['Erro 1.5: Erro de escrita',['../db/dda/md__testes_01e_01erros.html#erro-15-erro-de-escrita',1,'']]],
  ['de_20pokemon_20atual_20maior_20do_20que_20o_20total_11',['Erro 3.2: Número de pokemon atual maior do que o total',['../db/dda/md__testes_01e_01erros.html#erro-32-número-de-pokemon-atual-maior-do-que-o-total',1,'']]],
  ['de_20pokemon_20inválidos_12',['Erro 3.3: Atributos de pokemon inválidos',['../db/dda/md__testes_01e_01erros.html#erro-33-atributos-de-pokemon-inválidos',1,'']]],
  ['de_20pokemons_20negativo_20ou_20nulo_13',['Erro 3.1: Número de pokemons negativo ou nulo',['../db/dda/md__testes_01e_01erros.html#erro-31-número-de-pokemons-negativo-ou-nulo',1,'']]],
  ['de_20ponteiro_20e_20memória_14',['Erros de ponteiro e memória',['../db/dda/md__testes_01e_01erros.html#erros-de-ponteiro-e-memória',1,'']]],
  ['de_20tipagem_20de_20pokemons_15',['Erro de tipagem de pokemons',['../db/dda/md__testes_01e_01erros.html#erro-de-tipagem-de-pokemons',1,'']]],
  ['de_20um_20arquivo_20inexistente_16',['Erro 1.1: Abertura de um arquivo inexistente',['../db/dda/md__testes_01e_01erros.html#erro-11-abertura-de-um-arquivo-inexistente',1,'']]],
  ['de_20um_20arquivo_20para_20gravação_17',['Erro 1.2: Abertura inválida de um arquivo para gravação',['../db/dda/md__testes_01e_01erros.html#erro-12-abertura-inválida-de-um-arquivo-para-gravação',1,'']]],
  ['definitions_2eh_18',['definitions.h',['../d6/dc2/definitions_8h.html',1,'']]],
  ['descrição_19',['Descrição',['../index.html#descrição',1,'']]],
  ['descrição_20do_20algoritmo_20e_20procedimentos_20utilizados_20',['Descrição do algoritmo e procedimentos utilizados',['../index.html#descrição-do-algoritmo-e-procedimentos-utilizados',1,'']]],
  ['diagramas_21',['Diagramas',['../index.html#diagramas',1,'']]],
  ['divide_5flinha_22',['divide_linha',['../d5/d5e/file__utils_8c.html#ad8129b1c5e92e0eec41dbbddfe99b765',1,'divide_linha(char *line):&#160;file_utils.c'],['../d1/d9d/file__utils_8h.html#ad8129b1c5e92e0eec41dbbddfe99b765',1,'divide_linha(char *line):&#160;file_utils.c']]],
  ['divide_5flinha_23',['Divide_linha',['../index.html#divide_linha',1,'divide_linha'],['../db/dda/md__testes_01e_01erros.html#divide_linha-1',1,'divide_linha']]],
  ['do_20algoritmo_20e_20procedimentos_20utilizados_24',['Descrição do algoritmo e procedimentos utilizados',['../index.html#descrição-do-algoritmo-e-procedimentos-utilizados',1,'']]],
  ['do_20que_20o_20total_25',['Erro 3.2: Número de pokemon atual maior do que o total',['../db/dda/md__testes_01e_01erros.html#erro-32-número-de-pokemon-atual-maior-do-que-o-total',1,'']]]
];
